[package]
name = "table"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sprs = "0.10.0"
rug = "1.12.0"
ndarray = "0.14.0"
num-traits = "0.2.14"